# =============================================================================
# Simpsons Character Detection - YOLO Format Training Configuration
# =============================================================================
#
# Dataset: Simpsons Character Detection (Roboflow) - YOLO FORMAT
# Model: YOLOv9-Tiny (v9-t)
# Classes: 7 (abraham_grampa_simpson, bart_simpson, homer_simpson, lisa_simpson,
#             maggie_simpson, marge_simpson, ned_flanders)
#
# Usage:
#   python -m yolo.cli fit --config training-experiment/simpsons-yolo-train.yaml
#
# =============================================================================

# -----------------------------------------------------------------------------
# Trainer Configuration
# -----------------------------------------------------------------------------
trainer:
  max_epochs: 50
  accelerator: auto      # Supports: cuda, mps, cpu
  devices: auto          # Auto-detect available devices
  precision: 32          # Use 32 for MPS, 16-mixed for CUDA
  gradient_clip_val: 10.0
  accumulate_grad_batches: 1
  log_every_n_steps: 5
  check_val_every_n_epoch: 1

  # Callbacks
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: training-experiment/checkpoints-yolo
        monitor: val/mAP
        mode: max
        save_top_k: 3
        save_last: true
        save_on_train_epoch_end: false
        filename: "simpsons-yolo-epoch={epoch:02d}-mAP={val/mAP:.4f}"
        auto_insert_metric_name: false

    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/mAP
        mode: max
        patience: 20
        verbose: true
        check_on_train_epoch_end: false

    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

    - class_path: yolo.training.callbacks.YOLOProgressBar

    - class_path: yolo.training.callbacks.EvalDashboardCallback
      init_args:
        conf_prod: 0.25
        show_trends: true
        top_n_classes: 3

    # EMA: Exponential Moving Average
    - class_path: yolo.training.callbacks.EMACallback
      init_args:
        decay: 0.9999
        tau: 2000
        enabled: true

  # Logger
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: training-experiment/
        name: logs-yolo

# -----------------------------------------------------------------------------
# Model Configuration
# -----------------------------------------------------------------------------
model:
  # Architecture
  model_config: v9-t
  num_classes: 7         # Simpsons characters
  image_size: [640, 640]

  # Class names for metrics display
  class_names:
    - abraham_grampa_simpson
    - bart_simpson
    - homer_simpson
    - lisa_simpson
    - maggie_simpson
    - marge_simpson
    - ned_flanders

  # Optimizer
  optimizer: sgd
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005

  # LR Scheduler
  lr_scheduler: cosine
  lr_min_factor: 0.01

  # Warmup
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1

  # Loss weights
  box_loss_weight: 7.5
  cls_loss_weight: 0.5
  dfl_loss_weight: 1.5

  # Pretrained weights (transfer learning from COCO)
  weight_path: true

  # Layer Freezing (transfer learning)
  freeze_backbone: false
  freeze_until_epoch: 0

  # NMS settings
  nms_conf_threshold: 0.25
  nms_iou_threshold: 0.65
  nms_max_detections: 300
  save_metrics_plots: true

# -----------------------------------------------------------------------------
# Data Configuration (YOLO Format)
# -----------------------------------------------------------------------------
data:
  # Dataset format: 'coco' or 'yolo'
  format: yolo

  # Dataset paths (YOLO format)
  root: training-experiment/simpsons-yolo
  train_images: train/images
  train_labels: train/labels
  val_images: valid/images
  val_labels: valid/labels

  # DataLoader
  batch_size: 8
  num_workers: 4
  image_size: [640, 640]
  pin_memory: true

  # Multi-Image Augmentation
  mosaic_prob: 1.0
  mosaic_9_prob: 0.0
  mixup_prob: 0.15
  mixup_alpha: 32.0
  cutmix_prob: 0.0

  # Single-Image Augmentation
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 10.0
  translate: 0.1
  scale: 0.9
  shear: 0.0
  perspective: 0.0
  flip_lr: 0.5
  flip_ud: 0.0

  # Training Schedule
  close_mosaic_epochs: 10
